### ISSUE TITLE
License discussion

### ISSUE THREAD

**Issue by liannah** [UBC-MDS/bccovideda#67]
are we sure MIT license is the best ?

**Comment by liannah** [comment]
As per our discussion, I think we all agreed that as our package is open source and is created for the wider use of the public, we want the license that allows people to freely use, adapt, and build on our source code. In that sense MIT license, I think suits us the best.  

The other licenses to consider are 

- GPL: gives freedom to the users to use, build on, adapt, share, but any derivative work must be distributed under the same license. For example, they cannot use our code and make it not open source. 
- BSD: MIT license is compatible with BSD two clause license with an attribution clause. The other versions of BSD, namely three clauses, and four clause ones, I think are irrelevant for us, because our package is simple and our intentions were to make it as publicly available as possible, thus the commercial use is actually even desirable. Thus keeping it simple and without restrictions is my suggestion. 
- MIT: grants free access of usage of our package, as long as attribution is given when used. 

I believe, as per our discussion, MIT still remains the best license for us. Let me know, what you think guys, and do you confirm the initial thoughts and discussions. @imtvwy @vtaskaev1 @johnwslee

**Comment by johnwslee** [comment]
I definitely agree. I believe that MIT license is the one that fits the purpose of our package best.

**Comment by vtaskaev1** [comment]
I would also agree that the MIT license is most suitable license to our package. We welcome its use and adaptation under and an open source framework, and with proper attribution, there should be no issue should another license be applied to its adapted code.

**Comment by imtvwy** [comment]
I agree we should keeping using the MIT license.  
The vision of our project is to allow more people to use, build and contribute on our package.   Both MIT and BSD license should fit our purpose.  A bit research on the difference between the two is MIT license has explicitly included the documentation files in the license as "this software and associated documentation files" , while BSD includes "source and binary forms" only
Given that and both license are simple for the users to use, I will opt for MIT license.
